spring:
  application:
    name: gateway
  grpc:
    client:
      channels:
        registration-service:
          address: localhost:9090
  web:
    locale: en
    locale-resolver: fixed
  threads:
    virtual:
      enabled: true

server:
  port: 8080

